### ISSUE TITLE
Add requirements file (requirements.txt)

### ISSUE THREAD

**Issue by cw-andrews** [joefriedrich/Excel-Matrix-Rewrite#3]
Please add a requirements.txt file to your project root so that anyone who wants to use your project can easily clone the repo, create a virtualenv, install the required packages, *and* use what you built.

1. Create virtualenv using appropriate python version.
2. Install required packages.
3. Make sure you can use your project (that you aren't missing any required packages, etc.).
4. Run the following from your project **root**:
~~~
pip freeze > requirements.txt
~~~
5. Add the new file to your repo.

Now anyone can git clone your repo, create a virtualenv, and run the following to be able to run use your work!
~~~
pip install -r requirements.txt
~~~

**Comment by cw-andrews** [comment]
Come-on bro- aren't you going to close this?

**Comment by joefriedrich** [comment]
Sry issues IRL.  Will try to close this weekend.

**Comment by cw-andrews** [comment]
Just giving you a hard time man - no worries.

**Comment by joefriedrich** [comment]
Created requirements.txt file.
